import {
  IconLayout,
  IconUserCheck,
  IconSchool,
  IconCalendar,
  IconBook,
  IconUsers,
  IconUserCog,
  IconShield,
  IconClipboardList,
  IconClock,
  IconCreditCard,
  IconChartHistogram,
  IconSettings,
  IconDownload,
  IconDeviceLaptop,
  IconDeviceImacUp,
  IconAlertCircle,
  IconFileDescription,
  IconMessage,
  IconServerBolt,
  IconUsersGroup,
  IconCurrencyDollar,
  IconChartInfographic,
  IconNotebook,
  IconTrendingUp,
  IconWallet,
  IconChalkboardTeacher,
  IconFileCertificate,
  IconFileText,
  IconHome,
  IconChartBarPopular,
  IconArticle,
  IconShoppingCart,
  IconInfoCircle,
  IconTrophy,
  IconNews,
  IconBrandCodecov,
  IconStackMiddle,
  IconBriefcase,
  IconShoppingBag,
  IconMail,
} from "@tabler/icons-react";

export const homeNavLinks = [
  { slug: "/", label: "Home", icon: IconHome },
  { slug: "/about", label: "About", icon: IconAlertCircle },
  { slug: "/services", label: "Services", icon: IconBriefcase },
  { slug: "/marketplace", label: "Marketplace", icon: IconShoppingBag },
  { slug: "/contact", label: "Contact", icon: IconMail },
];

export const homeNavLinksMobile = [
  { slug: "/", label: "Home", icon: IconHome },
  { slug: "/about", label: "About", icon: IconAlertCircle },
  { slug: "/brands", label: "Brands", icon: IconUsersGroup, comingSoon: true },
  { slug: "/blog", label: "Blog", icon: IconArticle },
  {
    slug: "/ecosystem",
    label: "Ecosystem",
    icon: IconStackMiddle,
    comingSoon: true,
  },
  {
    slug: "/services",
    label: "Services",
    icon: IconBriefcase,
    comingSoon: true,
  },
  {
    slug: "/marketplace",
    label: "Marketplace",
    icon: IconShoppingBag,
  },
  { slug: "/community", label: "Community", icon: IconUsers, comingSoon: true },
  { slug: "/contact", label: "Contact", icon: IconMail },
];
